import { Hex } from "@teiki/protocol/types";

import {
  NEXT_PUBLIC_PROJECT_AT_MPH,
  NEXT_PUBLIC_PROOF_OF_BACKING_MPH,
  NEXT_PUBLIC_LEGACY_PROOF_OF_BACKING_MPH,
  NEXT_PUBLIC_PROTOCOL_NFT_MPH,
  NEXT_PUBLIC_TX_TIME_END_PADDING,
  NEXT_PUBLIC_TX_TIME_START_PADDING,
  NEXT_PUBLIC_TEIKI_MPH,
} from "../../config/client";

export const TX_TIME_START_PADDING = Number(NEXT_PUBLIC_TX_TIME_START_PADDING);
export const TX_TIME_END_PADDING = Number(NEXT_PUBLIC_TX_TIME_END_PADDING);

export const PROJECT_AT_MPH: Hex = NEXT_PUBLIC_PROJECT_AT_MPH;
export const PROOF_OF_BACKING_MPH: Hex = NEXT_PUBLIC_PROOF_OF_BACKING_MPH;
export const PROTOCOL_NFT_MPH: Hex = NEXT_PUBLIC_PROTOCOL_NFT_MPH;
export const TEIKI_MPH: Hex = NEXT_PUBLIC_TEIKI_MPH;
export const RATIO_MULTIPLIER = BigInt(1e6);

export const LEGACY_PROOF_OF_BACKING_MPH: Hex | null =
  NEXT_PUBLIC_LEGACY_PROOF_OF_BACKING_MPH;
